export const projectCategories = [
  "Agriculture",
  "Animation",
  "Artificial Intelligence",
  "Blockchain",
  "Community",
  "Culture & Heritage",
  "E-commerce",
  "Education",
  "Environment",
  "Fashion & Design",
  "Film/Video",
  "Food & Beverage",
  "Gaming",
  "Hardware",
  "Healthcare",
  "Infrastructure & Energy",
  "Music",
  "Real Estate",
  "Services",
  "Smart Devices",
  "Software",
  "Sports",
  "Startups",
  "Tele-communications",
  "Transportation",
  "Visual Arts",
].sort();
