// Generated by Supabase from the live schema. Do not edit by hand.
// Regenerate after any migration:
//   supabase gen types typescript --project-id eqnheftmstapthlblpbx > src/lib/supabase/database.types.ts
//
// One caveat the generator cannot express: numeric(78,0) columns are typed
// `number` here, and a JS number cannot hold an i128 exactly. Any query that
// reads a *_raw column selects it cast to text so it arrives as a string —
// see src/lib/data/projects.ts. Writes accept `string` for the same reason.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/** Exact on-chain amounts cross the wire as text. */
type Raw = number | string;

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.15" };
  public: {
    Tables: {
      auth_challenges: {
        Row: { created_at: string; expires_at: string; nonce: string; public_key: string };
        Insert: { created_at?: string; expires_at?: string; nonce: string; public_key: string };
        Update: { created_at?: string; expires_at?: string; nonce?: string; public_key?: string };
        Relationships: [];
      };
      claim_requests: {
        Row: { created_at: string; id: string; project_id: string; requested_by: string };
        Insert: { created_at?: string; id?: string; project_id: string; requested_by: string };
        Update: { created_at?: string; id?: string; project_id?: string; requested_by?: string };
        Relationships: [];
      };
      contract_events: {
        Row: {
          contract_id: string;
          created_at: string;
          error: string | null;
          event_id: string;
          id: string;
          ledger: number;
          ledger_closed_at: string | null;
          payload: Json;
          processed_at: string | null;
          topic1: string;
          topic2: string;
        };
        Insert: {
          contract_id: string;
          created_at?: string;
          error?: string | null;
          event_id: string;
          id?: string;
          ledger: number;
          ledger_closed_at?: string | null;
          payload?: Json;
          processed_at?: string | null;
          topic1?: string;
          topic2?: string;
        };
        Update: {
          contract_id?: string;
          created_at?: string;
          error?: string | null;
          event_id?: string;
          id?: string;
          ledger?: number;
          ledger_closed_at?: string | null;
          payload?: Json;
          processed_at?: string | null;
          topic1?: string;
          topic2?: string;
        };
        Relationships: [];
      };
      indexer_state: {
        Row: { key: string; updated_at: string; value: number };
        Insert: { key: string; updated_at?: string; value: number };
        Update: { key?: string; updated_at?: string; value?: number };
        Relationships: [];
      };
      kyc_requests: {
        Row: {
          consent_given: boolean;
          created_at: string;
          date_of_birth: string | null;
          details_hash: string;
          document_expires_on: string | null;
          document_path: string;
          document_type: string;
          email: string;
          full_name: string;
          id: string;
          id_number: string | null;
          rejection_reason: string;
          residential_address: string | null;
          status: string;
          stellar_address: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          consent_given?: boolean;
          created_at?: string;
          date_of_birth?: string | null;
          details_hash: string;
          document_expires_on?: string | null;
          document_path: string;
          document_type: string;
          email: string;
          full_name: string;
          id?: string;
          id_number?: string | null;
          rejection_reason?: string;
          residential_address?: string | null;
          status?: string;
          stellar_address: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          consent_given?: boolean;
          created_at?: string;
          date_of_birth?: string | null;
          details_hash?: string;
          document_expires_on?: string | null;
          document_path?: string;
          document_type?: string;
          email?: string;
          full_name?: string;
          id?: string;
          id_number?: string | null;
          rejection_reason?: string;
          residential_address?: string | null;
          status?: string;
          stellar_address?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          caption: string;
          created_at: string;
          id: string;
          is_read: boolean;
          project_id: string | null;
          title: string;
          url: string | null;
          user_id: string;
        };
        Insert: {
          caption?: string;
          created_at?: string;
          id?: string;
          is_read?: boolean;
          project_id?: string | null;
          title: string;
          url?: string | null;
          user_id: string;
        };
        Update: {
          caption?: string;
          created_at?: string;
          id?: string;
          is_read?: boolean;
          project_id?: string | null;
          title?: string;
          url?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      platform_admins: {
        Row: { display_name: string; email: string; granted_at: string; granted_by: string | null; id: string; note: string; user_id: string | null; wallet_address: string | null };
        Insert: { display_name?: string; email: string; granted_at?: string; granted_by?: string | null; id?: string; note?: string; user_id?: string | null; wallet_address?: string | null };
        Update: { display_name?: string; email?: string; granted_at?: string; granted_by?: string | null; id?: string; note?: string; user_id?: string | null; wallet_address?: string | null };
        Relationships: [];
      };
      admin_audit_log: {
        Row: { action: string; actor_id: string | null; created_at: string; detail: string; id: string; target_email: string };
        Insert: { action: string; actor_id?: string | null; created_at?: string; detail?: string; id?: string; target_email?: string };
        Update: { action?: string; actor_id?: string | null; created_at?: string; detail?: string; id?: string; target_email?: string };
        Relationships: [];
      };
      platform_settings: {
        Row: { fee_wallet_email: string; id: boolean; updated_at: string };
        Insert: { fee_wallet_email?: string; id?: boolean; updated_at?: string };
        Update: { fee_wallet_email?: string; id?: boolean; updated_at?: string };
        Relationships: [];
      };
      project_moderation: {
        Row: { project_id: string; state: "pending" | "approved" | "rejected"; flagged_by: string | null; flagged_at: string; decided_at: string | null; reason: string };
        Insert: { project_id: string; state?: "pending" | "approved" | "rejected"; flagged_by?: string | null; flagged_at?: string; decided_at?: string | null; reason?: string };
        Update: { project_id?: string; state?: "pending" | "approved" | "rejected"; flagged_by?: string | null; flagged_at?: string; decided_at?: string | null; reason?: string };
        Relationships: [];
      };
      project_approval_votes: {
        Row: { project_id: string; voter_id: string; approve: boolean; created_at: string };
        Insert: { project_id: string; voter_id: string; approve: boolean; created_at?: string };
        Update: { project_id?: string; voter_id?: string; approve?: boolean; created_at?: string };
        Relationships: [];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          display_name: string;
          id: string;
          last_login_at: string | null;
          stellar_public_key: string | null;
          updated_at: string;
          wallet_status: string;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          display_name?: string;
          id: string;
          last_login_at?: string | null;
          stellar_public_key?: string | null;
          updated_at?: string;
          wallet_status?: string;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          display_name?: string;
          id?: string;
          last_login_at?: string | null;
          stellar_public_key?: string | null;
          updated_at?: string;
          wallet_status?: string;
        };
        Relationships: [];
      };
      project_categories: {
        Row: {
          created_at: string;
          id: string;
          name: string;
          sort_order: number;
        };
        Insert: {
          created_at?: string;
          id?: string;
          name: string;
          sort_order?: number;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      project_milestones: {
        Row: {
          amount: number | null;
          amount_raw: Raw;
          created_at: string;
          description: string;
          id: string;
          milestone_id: number;
          project_id: string;
          proof: string;
          released: boolean;
          title: string;
          updated_at: string;
        };
        Insert: {
          amount_raw: Raw;
          created_at?: string;
          description?: string;
          id?: string;
          milestone_id: number;
          project_id: string;
          proof?: string;
          released?: boolean;
          title?: string;
          updated_at?: string;
        };
        Update: {
          amount_raw?: Raw;
          created_at?: string;
          description?: string;
          id?: string;
          milestone_id?: number;
          project_id?: string;
          proof?: string;
          released?: boolean;
          title?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          bond_amount: number | null;
          bond_amount_raw: Raw;
          bond_posted: boolean;
          category: string;
          created_at: string;
          created_on_chain_at: string;
          creator_address: string;
          creator_avatar_url: string;
          creator_display: string;
          currency: Database["public"]["Enums"]["currency_type"];
          current_funding: number | null;
          current_funding_raw: Raw;
          description: string;
          featured: boolean;
          funding_deadline: string;
          funding_goal: number | null;
          funding_goal_raw: Raw;
          id: string;
          image_url: string;
          is_public: boolean;
          last_updated_ledger: number;
          location: string;
          location_lat: number | null;
          location_lng: number | null;
          metadata_cid: string;
          project_id: string;
          released_total: number | null;
          released_total_raw: Raw;
          status: Database["public"]["Enums"]["project_status"];
          tagline: string;
          title: string;
          updated_at: string;
          vault_address: string;
        };
        Insert: {
          bond_amount_raw?: Raw;
          bond_posted?: boolean;
          category?: string;
          created_at?: string;
          created_on_chain_at: string;
          creator_address: string;
          creator_avatar_url?: string;
          creator_display?: string;
          currency?: Database["public"]["Enums"]["currency_type"];
          current_funding_raw?: Raw;
          description?: string;
          featured?: boolean;
          funding_deadline: string;
          funding_goal_raw: Raw;
          id?: string;
          image_url?: string;
          is_public?: boolean;
          last_updated_ledger?: number;
          location?: string;
          location_lat?: number | null;
          location_lng?: number | null;
          metadata_cid?: string;
          project_id: string;
          released_total_raw?: Raw;
          status?: Database["public"]["Enums"]["project_status"];
          tagline?: string;
          title: string;
          updated_at?: string;
          vault_address: string;
        };
        Update: {
          bond_amount_raw?: Raw;
          bond_posted?: boolean;
          category?: string;
          created_at?: string;
          created_on_chain_at?: string;
          creator_address?: string;
          creator_avatar_url?: string;
          creator_display?: string;
          currency?: Database["public"]["Enums"]["currency_type"];
          current_funding_raw?: Raw;
          description?: string;
          featured?: boolean;
          funding_deadline?: string;
          funding_goal_raw?: Raw;
          id?: string;
          image_url?: string;
          is_public?: boolean;
          last_updated_ledger?: number;
          location?: string;
          location_lat?: number | null;
          location_lng?: number | null;
          metadata_cid?: string;
          project_id?: string;
          released_total_raw?: Raw;
          status?: Database["public"]["Enums"]["project_status"];
          tagline?: string;
          title?: string;
          updated_at?: string;
          vault_address?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: {
      project_consensus: { Args: { pid: string }; Returns: { approvals: number; rejections: number; owners: number; needed: number; carried: boolean }[] };
      project_awaiting_consensus: { Args: { pid: string }; Returns: boolean };
      is_admin: { Args: Record<never, never>; Returns: boolean };
      is_admin_wallet: { Args: { addr: string }; Returns: boolean };
      purge_expired_auth_challenges: { Args: Record<never, never>; Returns: undefined };
      stroops_to_units: { Args: { raw: number }; Returns: number };
    };
    Enums: {
      currency_type: "USDC" | "USDT" | "XLM" | "WBTC" | "WETH";
      project_status:
        | "pending"
        | "approved"
        | "raising"
        | "funded"
        | "active"
        | "completed"
        | "failed"
        | "refunding"
        | "expired"
        | "rejected"
        | "hidden";
    };
    CompositeTypes: Record<never, never>;
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
