[package]
name    = "blkfndr-factory"
version = "0.1.0"
edition = "2021"
description = "BLKFNDR Crowdfunding Platform — Stellar Soroban Vault Factory smart contract"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
blkfndr-attestation = { path = "../blkfndr-attestation" }

[features]
testutils = ["soroban-sdk/testutils"]
