-- SUPERSEDED: intentionally a no-op.
--
-- This migration bound both kyc_requests write policies to the caller's linked
-- wallet (profiles.stellar_public_key). It was never applied to the live
-- database. 20261006155050_kyc_wallet_optional_at_submit, which is applied,
-- sets the same two policies with the same rule and one addition: a check may
-- be filed with no wallet yet (stellar_address is null) and the wallet
-- attached later by the server.
--
-- Its original statements set the policies without that null allowance. Kept
-- here, a `supabase db push` would find this version missing from the live
-- history and apply it after 20261006155050, silently refusing every
-- submission made without a wallet. So the statements are removed and the
-- version is kept, so every environment's history stays the same.
--
-- The rule it introduced -- an address on a check must be the caller's linked
-- wallet -- lives on in 20261006155050, and is only as good as
-- profiles.stellar_public_key, which 20261007100549_profiles_column_grants
-- makes writable by the service-role linkWallet path alone.

select 1;
